RazorAjaxControl/Models/RazorAjaxViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RazorAjaxControl.Models
{
    public class RazorAjaxViewModels
    {
        [Required]
        [Display(Name = "Text")]
        public string Text { get; set; }
    }
}

RazorAjaxControl/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RazorAjaxControl.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RazorAjaxControl/Controllers/RazorAjaxController.cs
// ------------------------------------------------ -----------------------  
// <copyright file = "RazorAjaxController.cs" company = "None">  
// Copyright (c) Permitir a distribuição deste código.  
// </copyright>  
// <author> Asma Khalid </author>  
// ------------------------------------------------ -----------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using RazorAjaxControl.Models;

namespace RazorAjaxControl.Controllers
{
    public class RazorAjaxController : Controller
    {
        #region Index view method.
        #region Get: /RazorAjax/Index  method.
        /// <summary>  
        /// Get: /RazorAjax/Index method.  
        /// </summary>  
        /// <returns>Return index view</returns>  
        public ActionResult Index()
        {
            try { }
            catch (Exception ex)
            {
                // Info  
                Console.Write(ex);
            }
            // Info.  
            return this.View();
        }
        #endregion
        #region POST: /RazorAjax/Index  
        /// <summary>  
        /// POST: /RazorAjax/Index  
        /// </summary>  
        /// <param name="model">Model parameter</param>  
        /// <returns>Return - RazorAjax content</returns>  
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Index(RazorAjaxViewModels model)
        {
            try
            {
                // Verification  
                if (ModelState.IsValid)
                {
                    // Info.  
                    return this.Json(new
                    {
                        EnableSuccess = true,
                        SuccessTitle = "Sucesso",
                        SuccessMsg = model.Text
                    });
                }
            }
            catch (Exception ex)
            {
                // Info  
                Console.Write(ex);
            }
            // Info  
            return this.Json(new
            {
                EnableError = true,
                ErrorTitle = "Erro",
                ErrorMsg = "Por favor, preencha o campo de texto!"
            });
        }
        #endregion 
        #endregion
    }
}

RazorAjaxControl/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

RazorAjaxControl/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RazorAjaxControl/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

RazorAjaxControl/Views/RazorAjax/Index.cshtml
@using RazorAjaxControl.Models
@model RazorAjaxControl.Models.RazorAjaxViewModels
@{
    ViewBag.Title = "ASP.NET MVC5: Formulario com Ajax e Razor";
}
<div class="row">
    <div class="panel-heading">
        <div class="col-md-8">
            <h3>
                <i class="fa fa-file-text-o"></i>
                <span>ASP.NET MVC5: Formulario com Ajax e Razor</span>
            </h3>
        </div>
    </div>
</div>
<div class="row">
    <section class="col-md-4 col-md-push-4">
        @using (Ajax.BeginForm("Index", "RazorAjax", 
            new AjaxOptions { HttpMethod = "POST", OnSuccess = "onAjaxRequestSuccess" },
            new { @id = "AjaxformId", @class = "form-horizontal", role = "form" })) 
        {
            @Html.AntiForgeryToken()
            <div class="well bs-component">
                <br />
                <div class="row">
                    <div class="col-md-12 col-md-push-2">
                        <div class="form-group">
                            <div class="col-md-10 col-md-pull-1">
                                @Html.TextBoxFor(m => m.Text, new { placeholder = Html.DisplayNameFor(m => m.Text), @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Text, "", new { @class = "text-danger custom-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-18">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4 col-md-push-2">
                                <div>
                                    <button type="submit"
                                            class="btn btn-warning"
                                            value="Process">
                                        <span class="ladda-label">Process</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </section>
</div>  

RazorAjaxControl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title> 
    @Styles.Render("~/Content/css") 
    @Scripts.Render("~/bundles/modernizr")
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
    <!-- Button Loader -->
    @Styles.Render("~/Plugin/Ladda-loader/css")
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <center>
                <p><strong>Cleberson Teodoro @DateTime.Now.Year</p>
            </center>
        </footer>
    </div> 
    @*Scripts*@ 
    @Scripts.Render("~/bundles/jquery") 
    @Scripts.Render("~/bundles/jqueryval") 
    @Scripts.Render("~/bundles/bootstrap")
    <!-- Custom Form -->
    @Scripts.Render("~/scripts/custom-form") @RenderSection("scripts", required: false)
</body>

</html>  